# Generated by Django 5.1 on 2024-09-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("id_proof", models.FileField(upload_to="id_proofs/")),
                (
                    "trainer_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=50,
                    ),
                ),
                ("batches", models.CharField(max_length=100)),
                ("batch_stage", models.CharField(max_length=100)),
                ("free_slots", models.IntegerField(default=0)),
                ("tech_stack", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
