# Generated by Django 5.1 on 2024-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="defaultpassword"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default="defaultpassword", max_length=255),
            preserve_default=False,
        ),
    ]
