# Generated by Django 5.1 on 2024-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cc", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "fee_quoted",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "batch_timing",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lead_status", models.CharField(max_length=50)),
                ("opportunity_status", models.CharField(max_length=50)),
                ("opportunity_stage", models.CharField(max_length=50)),
                ("demo_attended_stage", models.CharField(max_length=50)),
                ("visited_stage", models.CharField(max_length=50)),
                ("cold_lead_reason", models.CharField(max_length=255)),
                ("next_followup", models.DateField(blank=True, null=True)),
                ("lead_source", models.CharField(max_length=100)),
            ],
        ),
    ]
