# Generated by Django 5.1 on 2024-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="batch_timing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("7AM_8AM", "7AM_8AM"),
                    ("8AM_9AM", "8AM_9AM"),
                    ("9AM_10AM", "9AM_10AM"),
                    ("10AM_11AM", "10AM_11AM"),
                    ("11AM_12PM", "11AM_12PM"),
                    ("12PM_1PM", "12PM_1PM"),
                    ("1PM_2PM", "1PM_2PM"),
                    ("2PM_3PM", "2PM_3PM"),
                    ("3PM_4PM", "3PM_4PM"),
                    ("4PM_5PM", "4PM_5PM"),
                    ("5PM_6PM", "5PM_6PM"),
                    ("6PM_7PM", "6PM_7PM"),
                    ("7PM_8PM", "7PM_8PM"),
                    ("8PM_9PM", "8PM_9PM"),
                ],
                default="7AM_8AM",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="lead_status",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("NotContacted", "NotContacted"),
                    ("Attempted", "Attempted"),
                    ("WarmLead", "WarmLead"),
                    ("Opportunity", "Opportunity"),
                    ("AttendedDemo", "AttendedDemo"),
                    ("Visited", "Visited"),
                    ("Registered", "Registered"),
                    ("ColdLead", "ColdLead"),
                ],
                default="None",
                max_length=50,
            ),
        ),
    ]
