# Generated by Django 5.1 on 2024-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunties", "0002_alter_opportunity_batch_timing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="Stack",
            field=models.CharField(
                choices=[
                    ("Life Skills", "Life Skills"),
                    ("Study Abroad", "Study Abroad"),
                    ("HR", "HR"),
                ],
                default="Select Stack",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="class_mode",
            field=models.CharField(
                choices=[
                    ("International Online", "International Online"),
                    ("India Online", "India Online"),
                    ("BLR Classroom", "BLR Classroom"),
                    ("HYD Classroom", "Hyd Classroom"),
                ],
                default="HYDClassRoom",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="description",
            field=models.TextField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="lost_opportunity_reason",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("invalid_number", "Invalid Number"),
                    ("not_interested", "Not Interested"),
                    ("joined_another_institute", "Joined another institute"),
                    ("asking_free_course", "Asking free course"),
                    ("pay_after_placement", "Pay after Placement"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="batch_timing",
            field=models.CharField(
                choices=[
                    ("7AM_8AM", "7AM_8AM"),
                    ("8AM_9AM", "8AM_9AM"),
                    ("9AM_10AM", "9AM_10AM"),
                    ("10AM_11AM", "10AM_11AM"),
                    ("11AM_12PM", "11AM_12PM"),
                    ("12PM_1PM", "12PM_1PM"),
                    ("1PM_2PM", "1PM_2PM"),
                    ("2PM_3PM", "2PM_3PM"),
                    ("3PM_4PM", "3PM_4PM"),
                    ("4PM_5PM", "4PM_5PM"),
                    ("5PM_6PM", "5PM_6PM"),
                    ("6PM_7PM", "6PM_7PM"),
                    ("7PM_8PM", "7PM_8PM"),
                    ("8PM_9PM", "8PM_9PM"),
                ],
                default="7AM_8AM",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="demo_attended_stage",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("ready_to_join", "Ready to Join"),
                    ("advanced_discussion", "Advanced Discussion"),
                    ("call_not_answered", "Call Not Answered"),
                    ("visiting", "Visiting"),
                    ("fees_negotiation", "Fees Negotiation"),
                    ("batch_allocation", "Batch Allocation"),
                    ("need_time_this_week", "Need Time This Week"),
                    ("need_time_next_week", "Need Time Next Week"),
                    ("need_time_this_month", "Need Time This Month"),
                    ("needs_time_next_month", "Needs Time Next Month"),
                    ("special_requirements", "Special Requirements"),
                    ("closed_won_registered", "Closed Won (Registered)"),
                    ("closed_lost_cold_lead", "Closed Lost (Cold Lead)"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="opportunity_stage",
            field=models.CharField(
                choices=[
                    ("Select Opportunity Stage", "Select Opportunity Stage"),
                    ("None", "None"),
                    ("advanced_discussion", "Advanced Discussion"),
                    ("ready_to_join", "Ready To Join"),
                    ("visiting", "Visiting"),
                    ("fees_negotiation", "Fees Negotiation"),
                    ("batch_allocation", "Batch Allocation"),
                    ("interested_in_demo", "Interested in Demo"),
                    ("need_time_this_week", "Need Time This Week"),
                    ("need_time_next_week", "Need Time Next Week"),
                    ("need_time_this_month", "Need Time This Month"),
                    ("needs_time_next_month", "Needs Time Next Month"),
                    ("special_requirements", "Special Requirements"),
                    ("payment_link_sent", "Payment Link Sent"),
                    ("closed_won_registered", "Closed Won Registered"),
                    ("Busy & Asked a call back", "Busy & Asked a call back"),
                    ("Closed Lost", "Closed Lost"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="opportunity_status",
            field=models.CharField(
                choices=[
                    ("Visiting", "Visiting"),
                    ("visited", "visited"),
                    ("Demo Attended", "Demo Attended"),
                    ("Lost Opportunity", "Lost Opportunity"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="visited_stage",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("call_not_answered", "Call Not Answered"),
                    ("ready_to_join", "Ready To Join"),
                    ("fees_negotiation", "Fees Negotiation"),
                    ("batch_allocation", "Batch Allocation"),
                    ("interested_demo", "Interested Demo"),
                    ("special_requirements", "Special Requirements"),
                    ("need_time_this_week", "Need Time This Week"),
                    ("need_time_next_week", "Need Time Next Week"),
                    ("need_time_this_month", "Need Time This Month"),
                    ("need_time_next_month", "Need Time Next Month"),
                    ("closed_won_registered", "Closed Won(Registered)"),
                    ("closed_lost_cold_lead", "Closed Lost(Cold Lead)"),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
