# Generated by Django 5.1 on 2024-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_name", models.CharField(max_length=255)),
                ("campaign_type", models.CharField(max_length=255)),
                (
                    "campaign_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("campaign_date", models.DateField()),
                ("campaign_end_date", models.DateField()),
            ],
        ),
    ]
