# Generated by Django 5.1 on 2024-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_status",
            field=models.CharField(
                choices=[
                    ("select_campaign_name", "select_campaign_name"),
                    ("upcoming", "upcoming"),
                    ("ongoing", "ongoing"),
                    ("onhold", "onhold"),
                    ("completed", "Completed"),
                ],
                max_length=100,
            ),
        ),
    ]
