# Generated by Django 5.1 on 2024-09-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("createlead", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="createleads",
            old_name="TechStack",
            new_name="Stack",
        ),
        migrations.RenameField(
            model_name="createleads",
            old_name="fee_coated",
            new_name="fee_quoted",
        ),
        migrations.RenameField(
            model_name="createleads",
            old_name="date",
            new_name="next_fallow_up",
        ),
        migrations.RenameField(
            model_name="createleads",
            old_name="contact_no",
            new_name="phone",
        ),
    ]
