# Generated by Django 5.1 on 2024-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cc", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "fee_quoted",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "batch_timing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("7AM_8AM", "7AM_8AM"),
                            ("8AM_9AM", "8AM_9AM"),
                            ("9AM_10AM", "9AM_10AM"),
                            ("10AM_11AM", "10AM_11AM"),
                            ("11AM_12PM", "11AM_12PM"),
                            ("12PM_1PM", "12PM_1PM"),
                            ("1PM_2PM", "1PM_2PM"),
                            ("2PM_3PM", "2PM_3PM"),
                            ("3PM_4PM", "3PM_4PM"),
                            ("4PM_5PM", "4PM_5PM"),
                            ("5PM_6PM", "5PM_6PM"),
                            ("6PM_7PM", "6PM_7PM"),
                            ("7PM_8PM", "7PM_8PM"),
                            ("8PM_9PM", "8PM_9PM"),
                        ],
                        default="7AM_8AM",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("NotContacted", "NotContacted"),
                            ("Attempted", "Attempted"),
                            ("WarmLead", "WarmLead"),
                            ("Opportunity", "Opportunity"),
                            ("AttendedDemo", "AttendedDemo"),
                            ("Visited", "Visited"),
                            ("Registered", "Registered"),
                            ("ColdLead", "ColdLead"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
                ("opportunity_status", models.CharField(max_length=50)),
                ("opportunity_stage", models.CharField(max_length=50)),
                ("demo_attended_stage", models.CharField(max_length=50)),
                ("visited_stage", models.CharField(max_length=50)),
                ("cold_lead_reason", models.CharField(max_length=255)),
                ("next_followup", models.DateField(blank=True, null=True)),
                ("lead_source", models.CharField(max_length=100)),
            ],
        ),
    ]
