# Generated by Django 5.1 on 2024-09-23 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_course", models.CharField(max_length=255)),
                ("tech_stack", models.CharField(max_length=255)),
                ("course_comments", models.TextField(blank=True, null=True)),
                ("slack_access", models.BooleanField(default=False)),
                ("lms_access", models.BooleanField(default=False)),
                ("preferable_time", models.DateTimeField(blank=True, null=True)),
                ("batch_timing", models.DateTimeField(blank=True, null=True)),
                (
                    "mode_of_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("id_proof", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.IntegerField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("registered_date", models.DateField(blank=True, default=None)),
                ("batch_ids", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "attended_demo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "learner_owner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "learner_stage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("lead_created_time", models.DateTimeField(blank=True, null=True)),
                (
                    "counseling_done_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        default="Hyderabad",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learner.location",
                    ),
                ),
            ],
        ),
    ]
